### ISSUE TITLE
Use Firefox OS style app header

### ISSUE THREAD

**Issue by nt1m** [mdibaiee/Hawk#4]
It's usually fine to bring some personal touch to the app, but I think having a native header is really important, because it makes the app feel more integrated (the header is the most dominant element in the app, as it stands out the most).

I can submit a PR if you agree.

Btw, if you need any testing, feel free to ask me, I have a Flame device running the latest Firefox OS Nightly.

**Comment by mdibaiee** [comment]
I agree with you that the application must look familiar and integrated to users, but I see a lot of inconsistency in the style guide, I see the style guide has changed A LOT since I wrote my last application (Sketchy), and I see it's still changing, that's why I decided I was not going to follow the official style guide.

But still, if the style guide stabilizies and I like it, I might do this.

I would really appreciate testing, I'm waiting for early feedbacks from a few people I asked to test my app before releasing on Marketplace.

For now, I'm going to open an issue about back button which I would like to know your idea on.

**Comment by nt1m** [comment]
<blockquote>
I agree with you that the application must look familiar and integrated to users, but I see a lot of inconsistency in the style guide, I see the style guide has changed A LOT since I wrote my last application (Sketchy), and I see it's still changing, that's why I decided I was not going to follow the official style guide.
</blockquote>

The style guide hasn't changed much since Firefox OS 2.0 to be honest. The biggest change that happened is the one from Firefox OS 1.x to 2.0. I haven't noticed any significant differences ever since (I've been using my Firefox OS phone as my daily driver since last year).

<blockquote>
I would really appreciate testing
</blockquote>

Which version ? Works fine on my Firefox OS Nightly 2.5 (2.5 is the latest version, they went to 3.0, but then went back to 2.5 for some reason).

**Comment by mdibaiee** [comment]
If you say so, what would the header look like if we were to apply FxOS Style guide?

I personally used 2.5 to test my app at the beginning, the new Device Storage API is great, fast and flexible. But then I realised I had to polyfill the old API in order for 2.0+ devices to work.

The old API is veeeeeeeeeery slow and stupid I have to say, sadly. I installed a 2.2 to test this, but because I don't have a Firefox OS developer phone, but a Nexus 4 which I manually flashed FxOS on, it's very buggy, I can't quiet test it well, scrolling doesn't work, tapping doesn't work as it should be, etc.

I would appreciate it if you could test on 2.0 or 2.2, thanks Tim!

**Comment by nt1m** [comment]
![2015-09-20-17-02-25](https://cloud.githubusercontent.com/assets/1795135/9981515/d00d8258-5fbf-11e5-94b0-0d7fca61639e.png)

**Comment by mdibaiee** [comment]
Let's do this! Can you make a PR please? thanks @nt1m

**Comment by nt1m** [comment]
@mdibaiee Awesome ! Will submit one by the end of this week (very likely this weekend, or if I have time, tomorrow). Feel free to ping me in case I forget.

**Comment by mdibaiee** [comment]
@nt1m btw I added you as collaborator

**Comment by nt1m** [comment]
@mdibaiee Thanks ! I have the changes locally, but I'll need a bit more time to polish things up. Hopefully I'll get to it this week. Got a few exams coming up.

**Comment by mdibaiee** [comment]
@nt1m: Thank you! Please take your time! I hope you good luck on exams :+1:

**Comment by nt1m** [comment]
@mdibaiee Thanks ! Here's the pull request as promised: #9 :)

**Comment by mdibaiee** [comment]
Thank you!
